// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "about.h"
// Quat - A 3D fractal generation program
// Copyright (C) 1997-2000 Dirk Meyer
// (email: dirk.meyer@studserv.uni-stuttgart.de)
// mail:  Dirk Meyer
//        Marbacher Weg 29
//        D-71334 Waiblingen
//        Germany
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#include "icon.xpm"

AboutBox::AboutBox() {
  { win = new Fl_Double_Window(415, 360, "About Quat");
    win->user_data((void*)(this));
    { state = new Fl_Box(150, 15, 250, 15);
      state->labelfont(1);
      state->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* state
    { Fl_Box* o = new Fl_Box(150, 70, 235, 45, "A 3D Fractal Generation Program\n        Eric C. Hill <eric@stochastic.com> 2\
021\n        Original Copyright (C) 1997-2002 Dirk Meyer\ndirk.meyer@@studserv\
.uni-stuttgart.de (defunct domain)");
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(25, 165, 365, 50, "This program is distributed under the terms of the\nGNU General Public Licens\
e Version 2.\n(Please read the file \'COPYING\' for details).");
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(25, 215, 385, 65, "This program uses the \"zlib\" library to write PNG files.\nMore info on zlib\
: http://www.zlib.org/\nThe user interface is built with FLTK (Fast Light Tool\
 Kit) http://www.fltk.org.\nThis also uses components from the Boost libraries\
 from http://boost.org.\n");
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    { note = new Fl_Box(25, 280, 390, 20);
      note->labelsize(12);
      note->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* note
    { ok_button = new Fl_Return_Button(155, 310, 115, 25, "OK");
      ok_button->labelsize(12);
      ok_button->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
    } // Fl_Return_Button* ok_button
    { icon = new PixWid(30, 5, 115, 105);
      icon->box(FL_NO_BOX);
      icon->color(FL_BACKGROUND_COLOR);
      icon->selection_color(FL_BACKGROUND_COLOR);
      icon->labeltype(FL_NORMAL_LABEL);
      icon->labelfont(0);
      icon->labelsize(14);
      icon->labelcolor(FL_FOREGROUND_COLOR);
      icon->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      icon->when(FL_WHEN_RELEASE);
    } // PixWid* icon
    win->set_modal();
    win->end();
  } // Fl_Double_Window* win
  icon->setPixmap(icon_xpm);
}

void AboutBox::run() {
  win->show();
  while (win->shown())
  {
  	Fl::wait();
  	for (;;) 
  	{
  		Fl_Widget *o = Fl::readqueue();
  		if (!o) break;
  		if (o == ok_button) win->hide();
  	}
  }
}

AboutBox::~AboutBox() {
  delete win;
}
