// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef WriteIni_h
#define WriteIni_h

#pragma warning(push, 0)
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>
#pragma warning(pop)

extern Fl_Double_Window* win;
extern Fl_Button *cancel_button;
extern Fl_Check_Button* OBJ;
extern Fl_Check_Button* VIEW;
extern Fl_Check_Button* COL;
extern Fl_Check_Button* OTHER;
extern Fl_Return_Button* ok_button;
bool WriteINI(int& mode);
#endif
